# Handwritten
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeconfig-operator
  namespace: kubeconfig-operator
spec:
  selector:
    matchLabels:
      app: kubeconfig-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: kubeconfig-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - image: ghcr.io/klaudworks/kubeconfig-operator:latest
          imagePullPolicy: IfNotPresent
          name: manager
          args:
            - "--incluster"
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
      serviceAccountName: kubeconfig-operator
      terminationGracePeriodSeconds: 10
