name: Docker Build and Push

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - README.md
      - docs/**
      - manifests/**
      - .vscode/**
      - .github/**
      - .gitignore
      - .pre-commit-config.yaml
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        id: semver
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: 1.0.9
          DEFAULT_BUMP: patch
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.new_tag }},${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max       
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            **Docker image**: `ghcr.io/klaudworks/kubeconfig-operator:${{ steps.semver.outputs.new_tag }}`
            **Full Changelog**: https://github.com/klaudworks/kubeconfig-operator/compare/${{ steps.semver.outputs.old_tag }}...${{ steps.semver.outputs.new_tag }}
          tag_name: ${{ steps.semver.outputs.new_tag }}
